### ISSUE TITLE
2024 Roadmap

### ISSUE THREAD

**Issue by haruband** [ingkle-oss/deltaquery#2]
These are issues working on.

### Query engine (duckdb)
- [ ] Data/metadata caching
- [ ] Query caching

### Query engine (datafusion)
- [ ] Implementing new query engine using datafusion
- [ ] Data/metadata caching
- [ ] Query caching

### Storage engine (delta)
- [ ] Implementing new deltatable engine using datafusion

### ADBC/FlightSQL
- [ ] FlightSQL bulk ingestion support

### Benchmarking
- [ ] Query engine (duckdb vs datafusion)
- [ ] Deltatable engine (polars vs datafusion)
- [ ] SQL queries (spark vs trino vs deltaquery)

We are waiting for your help.

**Comment by gurugio** [comment]
It is possible to apply io_uring for data store?

**Comment by haruband** [comment]
We are using the parquet extension of duckdb to read multiple parquet files. If you have an interest in io_uring, you'd better take a look at duckdb or arrow's objectstore. The following is a recent issue related with io_uring in arrow-rs.

https://github.com/apache/arrow-rs/issues/4631
